[build]
  command   = "npx prisma migrate deploy && pnpm run build"
  publish   = ".svelte-kit/output/client"    # SvelteKit のクライアント出力
  functions = ".svelte-kit/output/server"    # サーバー（API）エンドポイント出力

[functions]
  # ここで node_modules/.prisma/client フォルダを確実に含める
  included_files = [
    "node_modules/.prisma/client/**",
    "prisma/schema.prisma"
  ]
