[build]
  command   = "pnpm run build && npx prisma migrate deploy"
  publish   = ".svelte-kit/output/client"    # SvelteKit のクライアント出力
  functions = ".svelte-kit/output/server"    # サーバー（API）エンドポイント出力

# 環境変数は Netlify UI で設定するのでここには書きません
