[build]
  command   = "npx prisma migrate deploy && pnpm run build"
  publish   = ".svelte-kit/output/client"    # SvelteKit のクライアント出力
  functions = ".svelte-kit/output/server"    # サーバー（API）エンドポイント出力

# 環境変数は Netlify UI で設定するのでここには書きません
